spring:
 datasource:
  url: jdbc:mysql://localhost:3306/newdb
  username: root
  password: Admin1987
 jpa:
  database: mysql
  show-sql: true
  hibernate:
   ddl-auto: create-drop
 jackson:
  serialization:
   fail-on-empty-beans: false